
# Test config file
# use geth --needed-option dumpconfig to see how it will be in the file

[Eth]
NetworkId = 4

[Eth.Ethash]
DatasetDir = "/depot/ethdb/rinkeby/.ethash"

[Node]
DataDir = "/depot/ethdb/rinkeby"
